import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
  new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' }
  environment {
    appName = 'variable'
  }
  stages {
    stage('Fase # 1') {
          steps {
              script {
                    sh "echo 'hola mundo 1'"
              }
          }
    }

    stage('Fase # 2') {
          steps {
              script {
                    sh "echo 'hola mundo 2'"
              }
          }
        }
  }

  post {
      always {
          deleteDir()
          sh "echo 'fase always'"
      }
      success {
        sh "echo 'fase success'"
      }

      failure {
        sh "echo 'fase failure'"
      }
  }
}

