/*
  groovylint-disable 
                      CompileStatic, 
                      LineLength, 
                      MethodParameterTypeRequired, 
                      MethodReturnTypeRequired, 
                      NoDef, 
                      UnnecessaryPackageReference, 
                      UnusedImport 
*/
import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
  new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' }
  environment {
    appName = 'variable'
  }
  stages {
    stage('Fase # 1') {
          steps {
              script {
                    sh "echo 'Hola Mundo 1'"
              }
          }
    }

    stage('Fase # 2') {
          steps {
              script {
                    sh "echo 'Hola Mundo 2'"
              }
          }
        }
  }

  post {
      always {
          deleteDir()
          sh "echo 'Post Fase - Always'"
      }
      success {
        sh "echo 'Post Fase - Success'"
      }

      failure {
        sh "echo 'Post Fase - Failure'"
      }
  }
}

